export const serviceLists = [
  {
    id: 1,
    title: "Scholarship Guidance",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 2,
    title: "Visa Processing",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 3,
    title: "University Admission",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 4,
    title: "Career Counseling",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 5,
    title: "Accommodation Support",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 6,
    title: "Travel & Ticketing",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
  },
];

export const menuItems = [
  {
    id: 3,
    title: "Destination",
    link: "/destination",
    submenu: [
      { name: "Study in USA", href: "/destination/usa" },
      { name: "Study in Australia", href: "/destination/australia" },
      { name: "Study in Canada", href: "/destination/canada" },
      { name: "Study in Malaysia", href: "/destination/malaysia" },
      { name: "Study in Bangladesh", href: "/destination/bangladesh" },
      { name: "Study in Spain", href: "/destination/spain" },
    ],
  },
  { id: 2, title: "Services", link: "/service" },
  { id: 1, title: "Events", link: "/events" },
  { id: 4, title: "About Us", link: "/about" },
  { id: 5, title: "Contact Us", link: "/contact" },
];

export const heroSection = [
  {
    id: 1,
    image: "../../../assets/heroSection.webp",
  },
  {
    id: 2,
    image: "../../../assets/heroSection.webp",
  },
  {
    id: 3,
    image: "../../../assets/heroSection.webp",
  },
];

export const countryList = [
  { key: "afghanistan", label: "Afghanistan" },
  { key: "albania", label: "Albania" },
  { key: "algeria", label: "Algeria" },
  { key: "andorra", label: "Andorra" },
  { key: "angola", label: "Angola" },
  { key: "antigua_barbuda", label: "Antigua and Barbuda" },
  { key: "argentina", label: "Argentina" },
  { key: "armenia", label: "Armenia" },
  { key: "australia", label: "Australia" },
  { key: "austria", label: "Austria" },
  { key: "azerbaijan", label: "Azerbaijan" },
  { key: "bahamas", label: "Bahamas" },
  { key: "bahrain", label: "Bahrain" },
  { key: "bangladesh", label: "Bangladesh" },
  { key: "barbados", label: "Barbados" },
  { key: "belarus", label: "Belarus" },
  { key: "belgium", label: "Belgium" },
  { key: "belize", label: "Belize" },
  { key: "benin", label: "Benin" },
  { key: "bhutan", label: "Bhutan" },
  { key: "bolivia", label: "Bolivia" },
  { key: "bosnia_herzegovina", label: "Bosnia and Herzegovina" },
  { key: "botswana", label: "Botswana" },
  { key: "brazil", label: "Brazil" },
  { key: "brunei", label: "Brunei" },
  { key: "bulgaria", label: "Bulgaria" },
  { key: "burkina_faso", label: "Burkina Faso" },
  { key: "burundi", label: "Burundi" },
  { key: "cabo_verde", label: "Cabo Verde" },
  { key: "cambodia", label: "Cambodia" },
  { key: "cameroon", label: "Cameroon" },
  { key: "canada", label: "Canada" },
  { key: "central_african_republic", label: "Central African Republic" },
  { key: "chad", label: "Chad" },
  { key: "chile", label: "Chile" },
  { key: "china", label: "China" },
  { key: "colombia", label: "Colombia" },
  { key: "comoros", label: "Comoros" },
  { key: "congo", label: "Congo" },
  { key: "costa_rica", label: "Costa Rica" },
  { key: "croatia", label: "Croatia" },
  { key: "cuba", label: "Cuba" },
  { key: "cyprus", label: "Cyprus" },
  { key: "czechia", label: "Czechia" },
  { key: "denmark", label: "Denmark" },
  { key: "djibouti", label: "Djibouti" },
  { key: "dominica", label: "Dominica" },
  { key: "dominican_republic", label: "Dominican Republic" },
  { key: "ecuador", label: "Ecuador" },
  { key: "egypt", label: "Egypt" },
  { key: "el_salvador", label: "El Salvador" },
  { key: "equatorial_guinea", label: "Equatorial Guinea" },
  { key: "eritrea", label: "Eritrea" },
  { key: "estonia", label: "Estonia" },
  { key: "eswatini", label: "Eswatini" },
  { key: "ethiopia", label: "Ethiopia" },
  { key: "fiji", label: "Fiji" },
  { key: "finland", label: "Finland" },
  { key: "france", label: "France" },
  { key: "gabon", label: "Gabon" },
  { key: "gambia", label: "Gambia" },
  { key: "georgia", label: "Georgia" },
  { key: "germany", label: "Germany" },
  { key: "ghana", label: "Ghana" },
  { key: "greece", label: "Greece" },
  { key: "grenada", label: "Grenada" },
  { key: "guatemala", label: "Guatemala" },
  { key: "guinea", label: "Guinea" },
  { key: "guinea_bissau", label: "Guinea-Bissau" },
  { key: "guyana", label: "Guyana" },
  { key: "haiti", label: "Haiti" },
  { key: "honduras", label: "Honduras" },
  { key: "hungary", label: "Hungary" },
  { key: "iceland", label: "Iceland" },
  { key: "india", label: "India" },
  { key: "indonesia", label: "Indonesia" },
  { key: "iran", label: "Iran" },
  { key: "iraq", label: "Iraq" },
  { key: "ireland", label: "Ireland" },
  { key: "israel", label: "Israel" },
  { key: "italy", label: "Italy" },
  { key: "jamaica", label: "Jamaica" },
  { key: "japan", label: "Japan" },
  { key: "jordan", label: "Jordan" },
  { key: "kazakhstan", label: "Kazakhstan" },
  { key: "kenya", label: "Kenya" },
  { key: "kiribati", label: "Kiribati" },
  { key: "korea_north", label: "North Korea" },
  { key: "korea_south", label: "South Korea" },
  { key: "kuwait", label: "Kuwait" },
  { key: "kyrgyzstan", label: "Kyrgyzstan" },
  { key: "laos", label: "Laos" },
  { key: "latvia", label: "Latvia" },
  { key: "lebanon", label: "Lebanon" },
  { key: "lesotho", label: "Lesotho" },
  { key: "liberia", label: "Liberia" },
  { key: "libya", label: "Libya" },
  { key: "liechtenstein", label: "Liechtenstein" },
  { key: "lithuania", label: "Lithuania" },
  { key: "luxembourg", label: "Luxembourg" },
  { key: "madagascar", label: "Madagascar" },
  { key: "malawi", label: "Malawi" },
  { key: "malaysia", label: "Malaysia" },
  { key: "maldives", label: "Maldives" },
  { key: "mali", label: "Mali" },
  { key: "malta", label: "Malta" },
  { key: "marshall_islands", label: "Marshall Islands" },
  { key: "mauritania", label: "Mauritania" },
  { key: "mauritius", label: "Mauritius" },
  { key: "mexico", label: "Mexico" },
  { key: "micronesia", label: "Micronesia" },
  { key: "moldova", label: "Moldova" },
  { key: "monaco", label: "Monaco" },
  { key: "mongolia", label: "Mongolia" },
  { key: "montenegro", label: "Montenegro" },
  { key: "morocco", label: "Morocco" },
  { key: "mozambique", label: "Mozambique" },
  { key: "myanmar", label: "Myanmar" },
  { key: "namibia", label: "Namibia" },
  { key: "nauru", label: "Nauru" },
  { key: "nepal", label: "Nepal" },
  { key: "netherlands", label: "Netherlands" },
  { key: "new_zealand", label: "New Zealand" },
  { key: "nicaragua", label: "Nicaragua" },
  { key: "niger", label: "Niger" },
  { key: "nigeria", label: "Nigeria" },
  { key: "north_macedonia", label: "North Macedonia" },
  { key: "norway", label: "Norway" },
  { key: "oman", label: "Oman" },
  { key: "pakistan", label: "Pakistan" },
  { key: "palau", label: "Palau" },
  { key: "palestine", label: "Palestine State" },
  { key: "panama", label: "Panama" },
  { key: "papua_new_guinea", label: "Papua New Guinea" },
  { key: "paraguay", label: "Paraguay" },
  { key: "peru", label: "Peru" },
  { key: "philippines", label: "Philippines" },
  { key: "poland", label: "Poland" },
  { key: "portugal", label: "Portugal" },
  { key: "qatar", label: "Qatar" },
  { key: "romania", label: "Romania" },
  { key: "russia", label: "Russia" },
  { key: "rwanda", label: "Rwanda" },
  { key: "saudi_arabia", label: "Saudi Arabia" },
  { key: "singapore", label: "Singapore" },
  { key: "south_africa", label: "South Africa" },
  { key: "sri_lanka", label: "Sri Lanka" },
  { key: "uk", label: "United Kingdom" },
  { key: "usa", label: "United States" },
  { key: "custom", label: "Custom Country" },
];

export const StudyLevels = [
  { key: "undergraduate", label: "Undergraduate" },
  { key: "postgraduate", label: "Postgraduate" },
  { key: "phd", label: "PhD / Doctorate" },
  { key: "diploma", label: "Diploma / Certificate" },
  { key: "foundation", label: "Foundation Program" },
  { key: "language", label: "Language Course" },
  { key: "all", label: "All Levels" },
];
