stages:
  - install
  - build
  - deploy

install:
  image: node:20
  stage: install
  script:
    - npm install
    - npm install --platform=linux --arch=x64 sharp
  artifacts:
    paths:
      - node_modules
      - package.json
      - package-lock.json
  only:
    - main

build:
  image: node:20
  stage: build
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    paths:
      - .next
      - package.json
      - package-lock.json
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  dependencies:
    - build
  before_script:
    - apk add --no-cache openssh rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  script:
    - echo "Starting SSH deployment for SSR app"
    - |
      rsync -avz --exclude 'node_modules' --exclude '.gitignore' \
        .next package.json package-lock.json "$SSH_USER"@"$SSH_HOST":"$SSH_PATH"
    - ssh "$SSH_USER"@"$SSH_HOST" 'pkill -f "$SSH_PATH/server.js" || true; nohup node "$SSH_PATH/server.js" > app.log 2>&1 &'
  only:
    - main
