# Define stages
stages:
  - build
  - deploy

build:
  image: node:20
  stage: build
  script:
    - npm install
    - npm install --platform=linux --arch=x64 sharp
    - npm run build
  artifacts:
    paths:
      - .next
      - package.json
      - package-lock.json
  only:
    - deploy

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    # Install lftp for FTP deployment
    - apk add --no-cache lftp
  script:
    - echo "Starting FTP deployment for SSR app"
    - |
      lftp -u binaryhooks@binaryhooks.com,StrongPassword123! 192.250.235.24 -e "
        set ftp:ssl-allow no;
        set ssl:verify-certificate no;
        set ftp:passive-mode yes;
        
        # Exclude node_modules during the upload process
        mirror -R --exclude node_modules . /  # Upload all files except node_modules
        put package.json -o /package.json
        put package-lock.json -o /package-lock.json
        bye;
      "
  only:
    - deploy
